[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqJump = "c894b116-72e5-5b58-be3c-e6d8d4ac2b12"
DiffEqProblemLibrary = "a077e3f3-b75c-5d7f-a0c6-6bc4c8ec64a9"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Catalyst = "6, 7, 8, 9, 10, 12"
DataFrames = "0.21, 0.22, 1.0"
DiffEqBase = "6.39"
DiffEqJump = "6.9, 7, 8"
DiffEqProblemLibrary = "4.8"
ModelingToolkit = "5, 6, 7, 8"
OrdinaryDiffEq = "5.41, 6"
Plots = "1.4"
SciMLBenchmarks = "0.1"
