[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ODEInterfaceDiffEq = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
ApproxFun = "0.11, 0.12, 0.13"
DiffEqDevTools = "2.22"
LSODA = "0.6, 0.7"
ODEInterfaceDiffEq = "3.7"
OrdinaryDiffEq = "5.41, 6"
Plots = "1.4"
SciMLBenchmarks = "0.1"
Sundials = "4.2"
