[deps]
BlackBoxOptimizationBenchmarking = "4552ee2b-11da-5aef-8e78-0d48532001f1"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationEvolutionary = "cb963754-43f6-435e-8d4b-99009ff27753"
OptimizationMetaheuristics = "3aafef2f-86ae-4776-b337-85a36adf0b55"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
OptimizationNOMAD = "2cab0595-8222-4775-b714-9828e6a9e01b"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
OptimizationPRIMA = "72f8369c-a2ea-4298-9126-56167ce9cbc2"
OptimizationPyCMA = "fb0822aa-1fe5-41d8-99a6-e7bf6c238d3b"
OptimizationSciPy = "cce07bd8-c79b-4b00-aee8-8db9cce22837"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"

[compat]
BlackBoxOptimizationBenchmarking = "1"
Memoize = "0.4"
Optimization = "4, 5"
OptimizationBBO = "0.4"
OptimizationEvolutionary = "0.4"
OptimizationMetaheuristics = "0.3"
OptimizationNLopt = "0.3"
OptimizationNOMAD = "0.3"
OptimizationOptimJL = "0.4"
OptimizationOptimisers = "0.3"
OptimizationPRIMA = "0.3"
OptimizationPyCMA = "1"
OptimizationSciPy = "0.4.1"
Plots = "1.4"
SciMLBenchmarks = "0.1"
