[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
ODEInterfaceDiffEq = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReactionNetworkImporters = "b4db0fb7-de2a-5028-82bf-5021f5cfa881"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
BenchmarkTools = "1.2"
Catalyst = "10.1, 12"
DiffEqBase = "6.53"
DiffEqDevTools = "2.27"
LSODA = "0.6, 0.7"
ModelingToolkit = "7, 8"
ODEInterface = "0.5"
ODEInterfaceDiffEq = "3.8"
OrdinaryDiffEq = "5.56, 6"
Plots = "1.10"
ReactionNetworkImporters = "0.13"
SciMLBenchmarks = "0.1"
Sundials = "4.4"
TimerOutputs = "0.5"
