[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
GeometricIntegratorsDiffEq = "5a33fad7-5ce4-5983-9f5d-5f26ceab5c96"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
MethodOfLines = "94925ecb-adb7-4558-8ed8-f975c56a0bf4"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ODE = "c030b06c-0b6d-57c2-b091-7029874bd033"
ODEInterfaceDiffEq = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProfileSVG = "132c30aa-f267-4189-9183-c8a63c7e05e6"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
AlgebraicMultigrid = "0.5, 0.6"
BenchmarkTools = "1"
DiffEqDevTools = "2.30"
DomainSets = "0.6"
GeometricIntegratorsDiffEq = "0.2"
IncompleteLU = "0.2"
LSODA = "0.7"
LinearSolve = "1, 2"
MethodOfLines = "0.9, 0.10"
ModelingToolkit = "8"
ODE = "2.5"
ODEInterfaceDiffEq = "3.10"
OrdinaryDiffEq = "6.19"
ParameterizedFunctions = "5.3"
Plots = "1.4"
ProfileSVG = "0.2"
SciMLBenchmarks = "0.1"
StaticArrays = "1"
Sundials = "4.2"
Symbolics = "5"
TimerOutputs = "0.5"
