[deps]
BVProblemLibrary = "ded0fc24-dfea-4565-b1d9-79c027d14d84"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BoundaryValueDiffEq = "764a87c0-6b3e-53db-9096-fe964310641d"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
SimpleBoundaryValueDiffEq = "be0294bd-f90f-4760-ac4e-3421ce2b2da0"

[compat]
BVProblemLibrary = "0.1.4"
BenchmarkTools = "1"
BoundaryValueDiffEq = "5.16"
CairoMakie = "0.12, 0.13, 0.14"
DiffEqDevTools = "2.48"
NonlinearSolve = "4.5"
ODEInterface = "0.5"
OrdinaryDiffEq = "6"
Plots = "1.4"
SciMLBenchmarks = "0.1"
SimpleBoundaryValueDiffEq = "1.0.0"
