[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BoundaryValueDiffEq = "764a87c0-6b3e-53db-9096-fe964310641d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"

[compat]
BenchmarkTools = "1"
BoundaryValueDiffEq = "4, 5"
OrdinaryDiffEq = "6"
Plots = "1.13"
SciMLBenchmarks = "0.1"
