[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Surrogates = "6fc51010-71bc-11e9-0e15-a3fcc6593c49"
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"

[compat]
BenchmarkTools = "1"
CondaPkg = "0.2"
Plots = "1"
PrettyTables = "3"
PythonCall = "0.9"
Statistics = "1"
Surrogates = "7"
XGBoost = "2"
