name = "DiffEqBenchmarks"
uuid = "31c91b34-3c75-11e9-0341-95557aab0344"
authors = ["Chris Rackauckas, Yingbo Ma, Vaibhav Dixit"]
version = "0.1.0"

[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqBayes = "ebbdde9d-f333-5424-9be2-dbf1e9acfb5e"
DiffEqBiological = "eb300fae-53e8-50a0-950c-e21f52c2b7e0"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DiffEqJump = "c894b116-72e5-5b58-be3c-e6d8d4ac2b12"
DiffEqParamEstim = "1130ab10-4a5a-5621-a13d-e4788d82bd4c"
DiffEqProblemLibrary = "a077e3f3-b75c-5d7f-a0c6-6bc4c8ec64a9"
DiffEqUncertainty = "ef61062a-5684-51dc-bb67-a0fcdec5c97d"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
ODE = "c030b06c-0b6d-57c2-b091-7029874bd033"
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
ODEInterfaceDiffEq = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ParallelDataTransfer = "2dcacdae-9679-587a-88bb-8b444fb7085b"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReactionNetworkImporters = "b4db0fb7-de2a-5028-82bf-5021f5cfa881"
RecursiveFactorization = "f2c3362d-daeb-58d1-803e-2bc74f2840b4"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
ApproxFun = "0.11"
BlackBoxOptim = "0.5"
DataFrames = "0.19, 0.20, 0.21"
DiffEqBase = "6.7"
DiffEqBayes = "2.9"
DiffEqBiological = "4.0"
DiffEqDevTools = "2.15"
DiffEqJump = "6.2"
DiffEqParamEstim = "1.8"
DiffEqProblemLibrary = "4.5"
DiffEqUncertainty = "1.3"
DifferentialEquations = "6.9"
IJulia = "1.20"
LSODA = "0.6"
NLopt = "0.5, 0.6"
ODE = "2.5"
ODEInterface = "0.4"
ODEInterfaceDiffEq = "3.4"
OrdinaryDiffEq = "5.23"
ParallelDataTransfer = "0.5"
ParameterizedFunctions = "4.2, 5.0"
Plots = "0.27, 0.28, 0.29, 1.0"
ReactionNetworkImporters = "0.1"
RecursiveFactorization = "0.1"
SteadyStateDiffEq = "1.5"
Sundials = "3.8, 4.0"
TimerOutputs = "0.5"
Weave = "0.9, 0.10"
julia = "1"
