name = "SciMLBenchmarks"
uuid = "31c91b34-3c75-11e9-0341-95557aab0344"
authors = ["Chris Rackauckas, Yingbo Ma, Vaibhav Dixit"]
version = "0.1.3"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
GR_jll = "d2c73de3-f751-5644-a686-071e5b155ba9"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OMJulia = "0f4fe800-344e-11e9-2949-fb537ad918e1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
CSV = "0.10"
DataFrames = "1"
Git = "1.2"
IJulia = "1.21"
OMJulia = "0.3"
Weave = "0.10"
julia = "1"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Plots", "Test"]
