name = "SciMLBenchmarks"
uuid = "31c91b34-3c75-11e9-0341-95557aab0344"
version = "0.1.4"
authors = ["Chris Rackauckas, Yingbo Ma, Vaibhav Dixit"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OMJulia = "0f4fe800-344e-11e9-2949-fb537ad918e1"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[weakdeps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"

[extensions]
SciMLBenchmarksIJuliaExt = "IJulia"

[compat]
CSV = "0.10"
DataFrames = "1"
DiffEqDevTools = "2.49.0"
ExplicitImports = "1.14.0"
Git = "1.2"
IJulia = "1.21"
ModelingToolkit = "10.32.0"
OMJulia = "0.3"
OrdinaryDiffEq = "6.106.0"
Plots = "1.41.5"
PrecompileTools = "1"
Sundials = "5.1.0"
Weave = "0.10"
julia = "1"

[extras]
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ExplicitImports", "Plots", "Test"]
