name = "SciMLBenchmarks"
uuid = "31c91b34-3c75-11e9-0341-95557aab0344"
authors = ["Chris Rackauckas, Yingbo Ma, Vaibhav Dixit"]
version = "0.1.3"

[deps]
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
Git = "1.2"
IJulia = "1.21"
Weave = "0.10"
julia = "1"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Plots", "Test"]
