
name = "DiffEqBenchmarks"
uuid = "31c91b34-3c75-11e9-0341-95557aab0344"
authors = ["Chris Rackauckas, Yingbo Ma, Vaibhav Dixit"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
IJulia = "1.21"
Weave = "0.10"
julia = "1"
