[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JumpProcesses = "ccbc3e58-028d-4f4c-8cd5-9ae44345cda5"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PiecewiseDeterministicMarkovProcesses = "86206cdf-4603-54e0-bd58-22a2dcbf57aa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BenchmarkTools = "1.4"
Catalyst = "13.5"
DataStructures = "0.18"
DiffEqCallbacks = "2.34"
Distributions = "0.25"
JumpProcesses = "9.9"
LazySets = "2.11"
OrdinaryDiffEq = "6.58"
Parameters = "0.12"
PiecewiseDeterministicMarkovProcesses = "0.0.7"
Plots = "1.39"
RecursiveArrayTools = "2.38"
SciMLBenchmarks = "0.1"
StaticArrays = "1.7"
