[deps]
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
MethodOfLines = "94925ecb-adb7-4558-8ed8-f975c56a0bf4"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PDESystemLibrary = "d14f9848-fe58-4297-bd22-c1aba6f3000d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
DiffEqDevTools = "2"
DomainSets = "0.5, 0.6"
LinearSolve = "1, 2"
MethodOfLines = "0.9"
ModelingToolkit = "8"
OrdinaryDiffEq = "6"
PDESystemLibrary = "0.1"
Plots = "1"
SciMLBenchmarks = "0.1"
Sundials = "4"
