[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BoundaryValueDiffEq = "764a87c0-6b3e-53db-9096-fe964310641d"
BracketingNonlinearSolve = "70df07ce-3d50-431d-a3e7-ca6ddb60ac1e"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BenchmarkTools = "1"
BoundaryValueDiffEq = "5.16"
BracketingNonlinearSolve = "1.1"
CairoMakie = "0.12, 0.13, 0.15"
DiffEqDevTools = "2.48"
Interpolations = "0.15.1, 0.16"
ODEInterface = "0.5"
SciMLBenchmarks = "0.1"
StaticArrays = "1.9.8"
