[deps]
DASKR = "165a45c3-f624-5814-8e85-3bdf39a7becd"
DASSL = "e993076c-0cfd-5d6b-a1ac-36489fdf7917"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ODEInterfaceDiffEq = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
DASKR = "2"
DASSL = "2"
DiffEqDevTools = "2.30"
ModelingToolkit = "8"
ODEInterfaceDiffEq = "3.10"
OrdinaryDiffEq = "6.19"
Plots = "1"
SciMLBenchmarks = "0.1"
Sundials = "4.6"
julia = "1.6"
