[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
Nonconvex = "01bcebdf-4d21-426d-b5c4-6132c1619978"
NonconvexIpopt = "bf347577-a06d-49ad-a669-8c0e005493b8"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ADNLPModels = "0.7"
BenchmarkTools = "1"
ConcreteStructs = "0.2"
CondaPkg = "0.2"
DataFrames = "1"
Enzyme = "0.11, 0.12"
ForwardDiff = "0.10"
Ipopt = "1"
JuMP = "1.15"
ModelingToolkit = "8"
NLPModelsIpopt = "0.10"
Nonconvex = "2"
NonconvexIpopt = "0.4"
Optim = "1"
Optimization = "3"
OptimizationMOI = "0.1, 0.2, 0.3"
Plots = "1"
PowerModels = "0.19"
PrettyTables = "2"
PythonCall = "0.9"
ReverseDiff = "1"
SparseDiffTools = "2"
StableRNGs = "1"
Symbolics = "5"
