[deps]
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GalacticOptim = "a75be94c-b780-496d-a8a9-0878b188d577"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NeuralPDE = "315f7962-48a3-4962-8226-d0f33b1235f0"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Quadrature = "67601950-bd08-11e9-3c89-fd23fb4432d2"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"

[compat]
Cuba = "2"
Cubature = "1"
DiffEqFlux = "1"
Flux = "0.12.8, 0.13"
GalacticOptim = "2"
ModelingToolkit = "7, 8"
NeuralPDE = "4"
Optim = "1"
Plots = "1"
Quadrature = "1"
SciMLBenchmarks = "0.1"
