[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationCMAEvolutionStrategy = "bd407f91-200f-4536-9381-e4ba712f53f8"
OptimizationEvolutionary = "cb963754-43f6-435e-8d4b-99009ff27753"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BenchmarkTools = "1"
ForwardDiff = "0.10"
ModelingToolkit = "8"
Optimization = "3"
OptimizationBBO = "0.1, 0.2"
OptimizationCMAEvolutionStrategy = "0.1, 0.2"
OptimizationEvolutionary = "0.1, 0.2, 0.3"
OptimizationNLopt = "0.1, 0.2"
OptimizationOptimJL = "0.1, 0.2"
OptimizationOptimisers = "0.1, 0.2"
Plots = "1.13"
SciMLBenchmarks = "0.1"
Zygote = "0.6"
