[deps]
DelayDiffEq = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DiffEqProblemLibrary = "a077e3f3-b75c-5d7f-a0c6-6bc4c8ec64a9"

[compat]
DelayDiffEq = "5.24"
DiffEqDevTools = "2.22"
DiffEqProblemLibrary = "4.8"
