[deps]
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
DiffEqProblemLibrary = "a077e3f3-b75c-5d7f-a0c6-6bc4c8ec64a9"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ParallelDataTransfer = "2dcacdae-9679-587a-88bb-8b444fb7085b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"

[compat]
DiffEqNoiseProcess = "4.3, 5.0"
DiffEqProblemLibrary = "4.8, 5"
ParallelDataTransfer = "0.5"
Plots = "1.4"
SciMLBenchmarks = "0.1"
StochasticDiffEq = "6.23"
