[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
NBodySimulator = "0e6f8da7-a7fc-5c8b-a220-74e902c310f9"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
BenchmarkTools = "0.5, 0.6, 0.7, 1.0"
DataFrames = "0.21, 0.22, 1.0"
NBodySimulator = "1.3"
OrdinaryDiffEq = "5.41, 6"
Plots = "1.5"
ProgressLogging = "0.1"
SciMLBenchmarks = "0.1"
StaticArrays = "0.12, 1.0"
StatsPlots = "0.14, 0.15"
