[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"

[compat]
BenchmarkTools = "1"
NonlinearSolve = "1, 2, 3"
Plots = "1.13"
Roots = "2"
SciMLBenchmarks = "0.1"
