[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DiffEqPhysics = "055956cb-9e8b-5191-98cc-73ae4a59e68a"
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TaylorIntegration = "92b13dbe-c966-51a2-8445-caca9f8a7d42"

[compat]
DiffEqCallbacks = "2.13"
DiffEqPhysics = "3.2"
Elliptic = "1.0"
OrdinaryDiffEq = "6"
ParameterizedFunctions = "5.3"
Plots = "1.4"
PyPlot = "2.9"
SciMLBenchmarks = "0.1"
StaticArrays = "1.0"
Statistics = "1"
TaylorIntegration = "0.14"
