[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DiffEqGPU = "071ae1c0-96b5-11e9-1f6c-b1f57e9cae5c"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BenchmarkTools = "1"
CUDA = "5"
DiffEqGPU = "3"
OrdinaryDiffEq = "6"
Plots = "1"
SciMLBenchmarks = "0.1"
StaticArrays = "1"
