[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
IntegralsCuba = "e00cd5f1-6337-4131-8b37-28b2fe4cd6cb"
IntegralsCubature = "c31f79ba-6e32-46d4-a52f-182a8ac42a54"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NeuralPDE = "315f7962-48a3-4962-8226-d0f33b1235f0"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationFlux = "253f991c-a7b2-45f8-8852-8b9a9df78a86"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"

[compat]
Integrals = "3, 4"
IntegralsCuba = "0.2, 0.3"
IntegralsCubature = "0.2"
Lux = "0.4, 0.5"
ModelingToolkit = "8"
NeuralPDE = "5"
Optimization = "3"
OptimizationFlux = "0.1, 0.2"
OptimizationOptimJL = "0.1, 0.2"
Plots = "1"
QuasiMonteCarlo = "0.2"
SciMLBenchmarks = "0.1"
