[deps]
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NeuralPDE = "315f7962-48a3-4962-8226-d0f33b1235f0"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"

[compat]
DelimitedFiles = "1"
Integrals = "4"
Lux = "1"
MLDataDevices = "1"
ModelingToolkit = "9, 10"
NeuralPDE = "5"
Optimisers = "0.4"
OptimizationOptimJL = "0.4"
Plots = "1"
QuasiMonteCarlo = "0.3"
ReverseDiff = "1"
SciMLBenchmarks = "0.1"
