[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
ODEInterfaceDiffEq = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqCore = "bbf590c4-e513-4bbe-9b18-05decba2e5d8"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
LinearSolve = "2"
