[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
MINPACK = "4854310b-de5a-5eb6-a2a5-c1dee2bd17f9"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NonlinearProblemLibrary = "b7050fa9-e91f-4b37-bcee-a89a063da141"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
PolyesterForwardDiff = "98d1487c-24ca-40b6-b7ab-df2af84e126b"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
SpeedMapping = "f1835b91-879b-4a3f-a438-e4baacf14412"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
AlgebraicMultigrid = "0.6"
BenchmarkTools = "1"
CairoMakie = "0.11"
DiffEqBase = "6.142"
DiffEqDevTools = "2"
IncompleteLU = "0.2"
LaTeXStrings = "1"
LinearSolve = "2"
MINPACK = "1.2"
NLsolve = "4.5"
NonlinearProblemLibrary = "0.1"
NonlinearSolve = "3"
PolyesterForwardDiff = "0.1"
PrettyTables = "2"
SciMLBenchmarks = "0.1"
Setfield = "1"
SimpleNonlinearSolve = "1"
SparseDiffTools = "2"
SpeedMapping = "0.3"
StableRNGs = "1"
StaticArrays = "1"
Sundials = "4.22"
Symbolics = "5"
