[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
NonlinearProblemLibrary = "b7050fa9-e91f-4b37-bcee-a89a063da141"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
NonlinearSolveMINPACK = "c100e077-885d-495a-a2ea-599e143bf69d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
SciMLNLSolve = "e9a6253c-8580-4d32-9898-8661bb511710"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
DiffEqDevTools = "2"
SciMLBenchmarks = "0.1"
SimpleNonlinearSolve = "0.1"
