[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
MINPACK = "4854310b-de5a-5eb6-a2a5-c1dee2bd17f9"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NonlinearProblemLibrary = "b7050fa9-e91f-4b37-bcee-a89a063da141"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
SciMLBenchmarks = "31c91b34-3c75-11e9-0341-95557aab0344"
SpeedMapping = "f1835b91-879b-4a3f-a438-e4baacf14412"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
BenchmarkTools = "1"
CairoMakie = "0.11"
DiffEqBase = "6.142"
DiffEqDevTools = "2"
LaTeXStrings = "1"
LinearSolve = "2"
MINPACK = "1.2"
NLsolve = "4.5"
NonlinearProblemLibrary = "0.1"
NonlinearSolve = "3"
Plots = "1.39"
PrettyTables = "2"
SciMLBenchmarks = "0.1"
SpeedMapping = "0.3"
StaticArrays = "1"
Sundials = "4.22"
